language: php

php:
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --version
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
